apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
  namespace: monitoring
data:
  agent.yaml: |
    server:
      log_level: info

    positions:
      filename: /var/lib/agent/positions.yaml

    clients:
      - url: {{ .Values.agent.loki.url }}

    scrape_configs:
{{ toYaml .Values.agent.logs.scrapeConfigs | indent 6 }}