namespace: finagent-dbs
storage:
  className: finagent-nfs-prod
  size: 100Gi
model:
  pullEnabled: true
  name: llama3.2:1b
  names:
    - llama3.2:1b
resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "4"
    memory: 8Gi
