namespace: finagent-dbs
storage:
  className: finagent-nfs-prod
  size: 20Gi
model:
  pullEnabled: true
  name: llama3.2:3b
  names:
    - llama3.2:3b
resources:
  requests:
    cpu: "3"
    memory: 4Gi
  limits:
    cpu: "6"
    memory: 10Gi
