namespace: finagent-dbs
appsNamespace: finagent-apps
storage:
  className: finagent-nfs
  size: 3Gi
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "250m"
    memory: "512Mi"
